"""create client and score

Revision ID: 6343eda6593a
Revises: 
Create Date: 2023-11-11 18:37:10.249034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6343eda6593a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('contacted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('accessibility', sa.Float(), nullable=True),
    sa.Column('best_practices', sa.Float(), nullable=True),
    sa.Column('seo', sa.Float(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('profile_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('linkedin_prospects')
    # ### end Alembic commands ###
